name: CI

env:
  IMAGE_NAME: activemq-artemis-broker-init
  QUAY_NAMESPACE: ajaypratap1234

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      snapshot:
        description: 'Snapshot'
        required: false
        default: false
        type: boolean
      trigger_children:
        description: 'Trigger children'
        required: false
        default: false
        type: boolean

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Execute the tests
        run: ./run_test.sh

      - name: Update base image
        if: ${{ inputs.snapshot }}
        run: |
          BASE_IMAGE="quay.io/${{ secrets.QUAY_NAMESPACE }}/activemq-artemis-broker-kubernetes@$(skopeo inspect docker://quay.io/${{ secrets.QUAY_NAMESPACE }}/activemq-artemis-broker-kubernetes:snapshot | jq -r '.Digest')"
          sed -i "s~FROM.*~FROM ${BASE_IMAGE}~g" Dockerfile
          
      - name: Set outputs
        id: vars
        run: | 
         echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
         echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Check outputs
        run: | 
         echo ${{ steps.vars.outputs.sha_short }}
         echo ${{ steps.vars.outputs.date }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
         platforms: 'amd64,arm64'
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to image repository quay.io
        # Only login if not a PR, as PRs only trigger a Docker build and not a push
#         if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          
      - name: Build and Push the dev image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          # If this is a PR, we only build for AMD64. For PRs we only do a sanity check test to ensure Docker builds  work.
          # If this is not a PR (e.g. a tag or merge commit), also build for ARM64
          platforms: linux/amd64${{github.event_name!='pull_request' && ',linux/arm64' || ''}}
#           push: ${{ github.event_name == 'push' }}
          push: false
          tags: ajaypratap1234/${{env.IMAGE_NAME}}:dev.latest, ajaypratap1234/${{env.IMAGE_NAME}}:dev.${{ steps.vars.outputs.date }}.${{ steps.vars.outputs.sha_short }}
          labels: |
            quay.expires-after=90d
            git-sha=$GITHUB_SHA

      - name: Check the image
        run: >
         docker container run --name ajaypratap1234/$IMAGE_NAME:dev.latest yacfg --profile artemis/2.15.0/default_with_user_address_settings.yaml.jinja2

      - name: Push the snapshot image
        if: ${{ github.event_name == 'schedule' || inputs.snapshot }}
        run: >
          docker login --username=${{ secrets.QUAY_USERNAME }} --password=${{ secrets.QUAY_PASSWORD }} quay.io &&
          docker tag $IMAGE_NAME:latest quay.io/${{ env.QUAY_NAMESPACE }}/$IMAGE_NAME:snapshot &&
          docker push quay.io/${{ env.QUAY_NAMESPACE }}/$IMAGE_NAME:snapshot
